name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov psycopg
      - name: Wait for DB to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for Postgres..."
            sleep 2
          done
      - name: Load schema into test database
        run: |
          psql -h localhost -U $DB_USER -d $DB_NAME -f db/valorantProPlay3
        env:
          PGPASSWORD: ${{ env.DB_PASSWORD }}

      - name: Run tests with coverage
        run: PYTHONPATH=. pytest test_integration.py TestLoginManager.py --cov=. --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Package and simulate deployment
        run: |
          mkdir -p deploy
          zip -r deploy/project.zip *.py tests
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployed-package
          path: deploy/project.zip
